### ISSUE TITLE
Can't install on php 8.2 from repo.magento.com

### ISSUE THREAD

**Issue by di-ivanov** [magento/magento2-pwa#9] opened 2023-03-21 16:25 UTC
If you attempt composer install or update of magento/pwa package on php 8.2 using repo.magento.com will fail with following message.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/pwa 0.0.1 requires magento/module-contact-graph-ql-pwa 0.0.* -> satisfiable by magento/module-contact-graph-ql-pwa[0.0.1].
    - magento/pwa 0.1.0 requires magento/module-contact-graph-ql-pwa 0.1.* -> satisfiable by magento/module-contact-graph-ql-pwa[0.1.0].
    - magento/pwa[0.2.0, ..., 0.2.2] require magento/module-contact-graph-ql-pwa 0.2.* -> satisfiable by magento/module-contact-graph-ql-pwa[0.2.0, 0.2.1, 0.2.2].
    - magento/pwa 0.3.0 requires magento/module-contact-graph-ql-pwa 0.3.* -> satisfiable by magento/module-contact-graph-ql-pwa[0.3.0].
    - magento/pwa 0.4.0 requires magento/module-contact-graph-ql-pwa 0.4.* -> satisfiable by magento/module-contact-graph-ql-pwa[0.4.0].
    - magento/module-contact-graph-ql-pwa[0.0.1, ..., 0.2.0] require php ~7.3.0||~7.4.0 -> your php version (8.2.4) does not satisfy that requirement.
    - magento/module-contact-graph-ql-pwa[0.2.1, ..., 0.4.0] require php ~7.4.0||~8.1.0 -> your php version (8.2.4) does not satisfy that requirement.
    - Root composer.json requires magento/pwa * -> satisfiable by magento/pwa[0.0.1, ..., 0.4.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require magento/pwa:*" to figure out if any version is installable, or "composer require magento/pwa:^2.1" if you know which you need.

```

I can see that the repo was updated with php 8.2 support, but not sure why this is not picked by Magento's packagist server. Not sure how current package is related to `magento/pwa` at all, but seems to be the only resource that resembles the package.

**Comment by sippsolutions** [comment] 2023-04-06 12:17
+1
I can confirm that installing `magento/pwa` with Magento 2.4.6 and PHP 8.2 is currently NOT possbile.
We want to upgrade our customers - Can you please fix this asap? @eug123

**Comment by larsroettig** [comment] 2023-04-06 12:30
@adobe export issue to Jira project PWA

**Comment by larsroettig** [comment] 2023-04-06 12:36
hi @sippsolutions and @di-ivanov thanks for report I can reproduce

**Comment by chernenm** [comment] 2023-04-11 15:20
hi @di-ivanov, @sippsolutions, @larsroettig,

Thank you for reporting this issue.
PWA Studio version 13.0 is not compatible with PHP 8.2, we are planing to release a new version PWA 13.1 compatible with PHP 8.2 and Adobe Commerce 2.4.6 later in April 2023.

**Comment by chernenm** [comment] 2023-04-21 19:15
Hi @di-ivanov, @sippsolutions,

Please try the latest PWA 13.1 release https://github.com/magento/pwa-studio/releases/tag/v13.1.0

**Comment by glo42707** [comment] 2023-05-19 12:46
hey @di-ivanov 
request to please close this ticket since this was tested for https://github.com/magento/pwa-studio/releases/tag/v13.1.0 and working as expected.

**Closed as completed** 2023-05-27 17:05 UTC
